# Generated by Django 4.0.3 on 2022-03-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='clik Link Above TO Read Blog Post', max_length=250),
        ),
    ]
